[package]
name = "webrender_surfman"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
edition = "2018"
publish = false

[lib]
name = "webrender_surfman"
path = "lib.rs"

[dependencies]
euclid = "0.22"
surfman = "0.6"
surfman-chains = "0.7"

